# Generated by Django 3.2.9 on 2021-11-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrixlms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='date',
            new_name='date_added',
        ),
    ]
