# Generated by Django 3.2.9 on 2021-11-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixlms', '0002_auto_20211110_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.DateTimeField(max_length=400, null=True),
        ),
    ]
