# Generated by Django 3.2.9 on 2021-11-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrixlms', '0005_alter_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categoty',
            new_name='category',
        ),
    ]
