# Generated by Django 3.2.9 on 2021-11-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixlms', '0006_rename_categoty_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Reserved', 'Reserved'), ('Not Reserved', 'Not Reserved')], max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Literary Fiction', 'Literary Fiction'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Historical', 'Historical'), ('Romance', 'Romance'), ('Western', 'Western'), ('Bildungsroman', 'Bildungsroman'), ('Speculative Fiction', 'Speculative Fiction'), ('Speculative Fiction', 'Speculative Fiction'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Dystopian', 'Dystopian'), ('Magical Realism', 'Magical Realism'), ('Realist Literature', 'Realist Literature')], max_length=200, null=True),
        ),
    ]
