# Generated by Django 3.2.9 on 2021-11-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrixlms', '0007_auto_20211110_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrixlms.book'),
        ),
    ]
