# Generated by Django 3.0.5 on 2021-11-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixlms', '0011_auto_20211111_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Literary Fiction', 'Literary Fiction'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Historical', 'Historical'), ('Romance', 'Romance'), ('Western', 'Western'), ('Bildungsroman', 'Bildungsroman'), ('Speculative Fiction', 'Speculative Fiction'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Dystopian', 'Dystopian'), ('Magical Realism', 'Magical Realism'), ('Realist Literature', 'Realist Literature')], max_length=200, null=True),
        ),
    ]
