# Generated by Django 3.2.9 on 2021-11-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixlms', '0013_auto_20211112_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='book',
            name='imagename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='auth_user',
        ),
    ]
